### ISSUE TITLE
flex左右浮动布局

### ISSUE THREAD

**Issue by ickedesign** [ickedesign/Daily_Study#118]
``` html
<div class="container-header">
  <div class="left></div>
  </div class="right"></div>
</div>
```

``` css
.container-header {
  display: flex;
  width: 100%;

  .left,
  .right {
    flex: 1;
  }

  .right {
    display: flex;
    flex-direction: row-reverse;
  }
}
```
