### ISSUE TITLE
更好地设置图片，使用background来设置

### ISSUE THREAD

**Issue by ickedesign** [ickedesign/Daily_Study#37]
``` css
<style lang="less" scoped>
.banner-pic {
  display: block;
  width: 100%;
  height: 100%;
  background-image: url(../test.png)
  background-position: center center;
  background-repeat: no-repeat;
  background-size: cover;
}
</style>
```
