### ISSUE TITLE
否，首个子元素，循环在less中的写法

### ISSUE THREAD

**Issue by ickedesign** [ickedesign/Daily_Study#40]
否
``` css
.mx-filter-tab-item {
  min-width: 80px;

  &:not(:last-child):after {
    .setRightLine()
  }
}
```

className为edit-function__group下的第一个className名为el-checkbox的元素
``` css
.edit-function__group>.el-checkbox:first-child {

}
```

循环：
``` css
.list-item {
      // 激活后的状态
    &.active {
      background-color: #44445B;
      box-shadow: inset 3px 0 0 0 #3DA5FE;

      // 循环激活后的背景图片
      @imgKeys: workbench, customer_msg, history_msg;
      .for(@imgKeys);.each(@item){
        .menu__list-item-icon_@{item} {
          @url: %("./assets/%d-hl.png", @item);
          background-image: url(@url);
        }
      }
    }
}
```
