### ISSUE TITLE
css样式，不换行，超出加省略号

### ISSUE THREAD

**Issue by ickedesign** [ickedesign/Daily_Study#71]
``` html
<div class="wrap">
  <a>ssssssssssssssssssssssssssssssssssss</a>
</div>
```

``` css
.wrap {
    overflow: hidden;
    display: inline-block;
    max-width: 400px;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```
